// PigmentSDK helpers: subscription lifecycle, readiness guards, write wrappers.
// Every subscription and listener registered here is torn down by disposeAll().

var SDK = window.PigmentSDK;

// The SDK renamed the view subscription: data sources replaced vizualizations
// when Frames moved from View bindings to inline data sources, and calling the
// old name now throws. Resolve whichever name this workspace exposes rather
// than pinning one, so the same body runs on either build.
function sdkMethod(names) {
  for (var i = 0; i < names.length; i++) {
    if (SDK && typeof SDK[names[i]] === 'function') return names[i];
  }
  return null;
}

// Every callable on the SDK, for the error message when nothing matches.
function sdkSurface() {
  if (!SDK) return 'window.PigmentSDK is missing';
  var seen = {}, out = [], k, i;
  for (k in SDK) { if (typeof SDK[k] === 'function' && !seen[k]) { seen[k] = 1; out.push(k); } }
  var own = Object.getOwnPropertyNames(SDK);
  for (i = 0; i < own.length; i++) {
    k = own[i];
    if (typeof SDK[k] === 'function' && !seen[k]) { seen[k] = 1; out.push(k); }
  }
  return out.length ? out.join(', ') : 'no callable methods';
}

var SUB_DATA = sdkMethod(['useSubscribeToDataSource', 'subscribeToDataSource', 'subscribeToVizualization']);
var SUB_ITEMS = sdkMethod(['useSubscribeToItems', 'subscribeToItems']);

var _subs = [];
var _timers = [];
var _listeners = [];
var _observers = [];
var _bodyNodes = [];

function hasLoadingKind(arr) {
  for (var i = 0; i < arr.length; i++) {
    var item = arr[i];
    if (Array.isArray(item)) { if (hasLoadingKind(item)) return true; }
    else if (item && typeof item === 'object' && item.kind === 'loading') return true;
  }
  return false;
}

function isReady(data) {
  if (!data || !data.labels || !data.labels.columns.length) return false;
  return !hasLoadingKind(data.labels.rows) &&
         !hasLoadingKind(data.labels.columns) &&
         !hasLoadingKind(data.cells);
}

// Last string entry of a label path is the display name.
function labelName(path) {
  if (typeof path === 'string') return path;
  if (!Array.isArray(path)) return '';
  for (var i = path.length - 1; i >= 0; i--) {
    if (typeof path[i] === 'string') return path[i];
  }
  return '';
}

function labelAt(path, level) {
  if (!Array.isArray(path)) return labelName(path);
  var v = path[level];
  return typeof v === 'string' ? v : '';
}

function cell(data, c, r) {
  if (!data || !data.cells || !data.cells[c]) return null;
  var v = data.cells[c][r];
  if (v && typeof v === 'object') return null;
  return v;
}

// Index a data source's columns so pages can read by metric display name
// regardless of position. A data source may label its columns with the binding
// alias rather than the metric's display name, so register both: COL_ALIAS is
// generated by build.py and maps alias -> display name.
function columnIndex(data) {
  var idx = {};
  if (!data || !data.labels) return idx;
  for (var c = 0; c < data.labels.columns.length; c++) {
    var raw = labelName(data.labels.columns[c]);
    idx[raw] = c;
    if (typeof COL_ALIAS !== 'undefined' && COL_ALIAS[raw] !== undefined) {
      idx[COL_ALIAS[raw]] = c;
    }
  }
  return idx;
}

// Same idea for a data source whose single row is a metric (the scalar and
// import-summary sources): find a row by display name or by binding alias.
function rowByName(data, name) {
  if (!data || !data.labels) return -1;
  for (var r = 0; r < data.labels.rows.length; r++) {
    var raw = labelName(data.labels.rows[r]);
    if (raw === name) return r;
    if (typeof COL_ALIAS !== 'undefined' && COL_ALIAS[raw] === name) return r;
  }
  return -1;
}

// The data source hands back row-major data with no column labels:
//   { rows: [ { labels: [...], values: [...] } ], rowOffset, totalRowCount }
// Values arrive in the order the data source declares them, so DS_COLUMNS
// (generated by gen_bindings.py, injected by build.py) is what names them.
// Everything above this line still reads the older column-major grid, so the
// payload is adapted once here rather than in six pages.
function adaptGrid(dsName, raw) {
  var cols = (typeof DS_COLUMNS !== 'undefined' && DS_COLUMNS[dsName]) || [];
  var rows = (raw && raw.rows) || [];
  var grid = {
    labels: { rows: [], columns: cols.slice() },
    cells: [],
    rowOffset: (raw && raw.rowOffset) || 0,
    totalRowCount: (raw && raw.totalRowCount) || rows.length
  };
  grid.truncated = grid.totalRowCount > rows.length;
  var c, r;
  for (c = 0; c < cols.length; c++) grid.cells.push([]);
  for (r = 0; r < rows.length; r++) {
    var lab = rows[r].labels || [];
    grid.labels.rows.push(lab.length === 1 ? lab[0] : lab.slice());
    var vals = rows[r].values || [];
    for (c = 0; c < cols.length; c++) {
      grid.cells[c].push(vals[c] === undefined ? null : vals[c]);
    }
  }
  return grid;
}

// One object per row of a single-label data source, keyed the way the pages
// used to read list items: the row label under keyName, then every column.
function rowsAsItems(grid, keyName) {
  var out = [];
  if (!grid) return out;
  var cols = grid.labels.columns;
  for (var r = 0; r < grid.labels.rows.length; r++) {
    var o = {};
    o[keyName] = labelAt(grid.labels.rows[r], 0) || labelName(grid.labels.rows[r]);
    for (var c = 0; c < cols.length; c++) o[cols[c]] = cell(grid, c, r);
    out.push(o);
  }
  return out;
}

// Reference lists come back through their property data source, so the labels
// are the item names and the columns are the properties.
function listFromProps(grid) { return rowsAsItems(grid, 'Name'); }

function listFromNames(names) {
  var out = [];
  for (var i = 0; i < (names || []).length; i++) out.push({ Name: names[i] });
  return out;
}

function sortByOrder(arr) {
  arr.sort(function (a, b) {
    var ao = typeof a.Order === 'number' ? a.Order : 9999;
    var bo = typeof b.Order === 'number' ? b.Order : 9999;
    if (ao !== bo) return ao - bo;
    return String(a.Name).localeCompare(String(b.Name));
  });
  return arr;
}

// Reference lists for the dropdowns. Where the list has properties a page
// needs - Stage.Order, Use Case.CRM Codes - they come from its property data
// source, which also supplies the names; otherwise the item names are enough.
// spec: [{ alias: 'stage', ds: 'vwStageProps' }, { alias: 'salesMotion' }]
function subscribeRefLists(lists, spec, redraw, fail) {
  for (var i = 0; i < spec.length; i++) {
    (function (s) {
      if (s.ds) {
        subscribeView(s.ds, function (d) {
          lists[s.alias] = sortByOrder(listFromProps(d));
          redraw();
        }, fail);
      } else {
        subscribeList(s.alias, function (items) {
          lists[s.alias] = items;
          redraw();
        }, fail);
      }
    })(spec[i]);
  }
}

// A data source carries one value type, so each logical source is stored as
// several per-type parts (D18). They share their labels, so the parts are
// joined back into one grid on the row labels before a page ever sees them.
function labelKey(lab) {
  return typeof lab === 'string' ? lab : (lab || []).join('\u0001');
}

function mergeParts(parts, store) {
  var out = { labels: { rows: [], columns: [] }, cells: [], rowOffset: 0,
              totalRowCount: 0, truncated: false };
  var index = {}, p, r, c, g;

  for (p = 0; p < parts.length; p++) {
    g = store[parts[p]];
    if (!g) continue;
    out.truncated = out.truncated || !!g.truncated;
    if (g.totalRowCount > out.totalRowCount) out.totalRowCount = g.totalRowCount;
    for (r = 0; r < g.labels.rows.length; r++) {
      var k = labelKey(g.labels.rows[r]);
      if (index[k] === undefined) {
        index[k] = out.labels.rows.length;
        out.labels.rows.push(g.labels.rows[r]);
      }
    }
  }

  for (p = 0; p < parts.length; p++) {
    g = store[parts[p]];
    if (!g) continue;
    for (c = 0; c < g.labels.columns.length; c++) {
      var col = [];
      for (var n = 0; n < out.labels.rows.length; n++) col.push(null);
      for (r = 0; r < g.labels.rows.length; r++) {
        col[index[labelKey(g.labels.rows[r])]] = cell(g, c, r);
      }
      out.labels.columns.push(g.labels.columns[c]);
      out.cells.push(col);
    }
  }
  return out;
}

function subscribeView(alias, onReady, onErr, pageDefs, scroll) {
  var parts = (typeof DS_PARTS !== 'undefined' && DS_PARTS[alias]) || [alias];
  var store = {}, arrived = 0;
  for (var i = 0; i < parts.length; i++) {
    (function (part) {
      subscribePart(part, function (grid) {
        if (!store[part]) arrived++;
        store[part] = grid;
        // Wait for every part, otherwise a page would render against half its
        // columns and then flicker as the rest land.
        if (arrived === parts.length) onReady(mergeParts(parts, store));
      }, onErr, scroll);
    })(parts[i]);
  }
}

function subscribePart(alias, onReady, onErr, scroll) {
  var opts = {
    onData: function (data) {
      var grid = adaptGrid(alias, data);
      if (!isReady(grid)) return;
      onReady(grid);
    },
    onError: function (err) { if (onErr) onErr(err); },
    dynamicFilters: []
  };
  // 1,000 rows is the ceiling the SDK allows in one window. Sources return
  // only populated rows, so this covers the whole model many times over; a
  // source that did overflow reports it through grid.truncated.
  opts.scroll = scroll || { offset: 0, numberOfRows: 1000 };
  if (!SUB_DATA) {
    if (onErr) onErr(new Error('This Pigment build has no data-source subscription. SDK methods: ' + sdkSurface()));
    return null;
  }
  var sub;
  try {
    sub = SDK[SUB_DATA](alias, opts);
  } catch (e) {
    if (onErr) onErr(new Error((e && e.message ? e.message : 'Subscription failed') + ' (' + SUB_DATA + ' "' + alias + '")'));
    return null;
  }
  if (sub) _subs.push(sub);
  return sub;
}

function subscribeList(alias, onReady, onErr) {
  if (!SUB_ITEMS) {
    if (onErr) onErr(new Error('This Pigment build has no item subscription. SDK methods: ' + sdkSurface()));
    return null;
  }
  var sub;
  try {
    // Items are plain item names now, not objects: anything else a Frame shows
    // has to come from a data source over list properties (D17).
    sub = SDK[SUB_ITEMS](alias, {
      onData: function (d) { onReady(listFromNames((d && d.items) || []), !!(d && d.partialResult)); },
      onError: function (err) { if (onErr) onErr(err); }
    });
  } catch (e) {
    if (onErr) onErr(new Error((e && e.message ? e.message : 'Subscription failed') + ' (' + SUB_ITEMS + ' "' + alias + '")'));
    return null;
  }
  if (sub) _subs.push(sub);
  return sub;
}

// A subscription may come back as an object with unsubscribe() or as the
// unsubscribe function itself; repaging may not be offered at all.
function stopSub(sub) {
  if (!sub) return;
  try {
    if (typeof sub === 'function') sub();
    else if (typeof sub.unsubscribe === 'function') sub.unsubscribe();
  } catch (e) {}
}

function debounce(fn, ms) {
  var t = null;
  function wrapped() {
    var args = arguments;
    if (t) clearTimeout(t);
    t = setTimeout(function () { t = null; fn.apply(null, args); }, ms);
    _timers.push(t);
  }
  return wrapped;
}

function on(target, type, handler) {
  target.addEventListener(type, handler);
  _listeners.push({ target: target, type: type, handler: handler });
}

function trackObserver(o) { _observers.push(o); return o; }
function trackBodyNode(n) { _bodyNodes.push(n); return n; }

function disposeAll() {
  for (var i = 0; i < _subs.length; i++) stopSub(_subs[i]);
  for (var j = 0; j < _timers.length; j++) clearTimeout(_timers[j]);
  for (var k = 0; k < _listeners.length; k++) {
    var L = _listeners[k];
    try { L.target.removeEventListener(L.type, L.handler); } catch (e) {}
  }
  for (var m = 0; m < _observers.length; m++) {
    try { _observers[m].disconnect(); } catch (e) {}
  }
  for (var n = 0; n < _bodyNodes.length; n++) {
    var el = _bodyNodes[n];
    if (el && el.parentNode) el.parentNode.removeChild(el);
  }
  _subs = []; _timers = []; _listeners = []; _observers = []; _bodyNodes = [];
}

// ---- writes -------------------------------------------------------------
// Each resolves to {ok:true} or {ok:false, message} so callers can revert the
// field and surface the SDK's own message rather than a generic failure.

function writeItem(listAlias, itemName, values) {
  return SDK.editItem(listAlias, itemName, values)
    .then(function () { toast('Saved'); return { ok: true }; })
    .catch(function (e) {
      var msg = (e && e.message) ? e.message : 'Could not save';
      toast(msg, true);
      return { ok: false, message: msg };
    });
}

function createItem(listAlias, values) {
  return SDK.addItem(listAlias, values)
    .then(function () { return { ok: true }; })
    .catch(function (e) {
      var msg = (e && e.message) ? e.message : 'Could not create';
      return { ok: false, message: msg };
    });
}

function writeValue(metricAlias, coords, value) {
  return SDK.editValue(metricAlias, coords, value)
    .then(function () { toast('Saved'); return { ok: true }; })
    .catch(function (e) {
      var msg = (e && e.message) ? e.message : 'Could not save';
      toast(msg, true);
      return { ok: false, message: msg };
    });
}
