// A stand-in for window.PigmentSDK, implementing the contract the ZZ SDK Probe
// observed in the live workspace (decisions D16-D18):
//   subscribeToDataSource(name, {onData, onError, dynamicFilters, scroll})
//     -> { updateDynamicFilters, updateScroll, unsubscribe }
//   onData({ rows: [{ labels: [...], values: [...] }], rowOffset, totalRowCount })
//   subscribeToItems(alias, {onData}) -> onData({ items: ["name", ...] })
// Nothing here talks to Pigment: FIXTURES is generated by gen_fixtures.py so the
// bundles can be rendered, screenshotted and error-checked without a login.
(function () {
  var errors = [];
  function record(kind, msg) {
    errors.push(kind + ': ' + msg);
    var box = document.getElementById('__errors');
    if (box) box.textContent = errors.join('\n');
  }
  window.__harnessErrors = errors;
  window.addEventListener('error', function (e) {
    record('window.onerror', (e.message || '') + ' @ ' + (e.filename || '') + ':' + (e.lineno || ''));
  });
  window.addEventListener('unhandledrejection', function (e) {
    var r = e.reason;
    record('unhandledrejection', (r && r.message) ? r.message : String(r));
  });
  var realError = console.error;
  console.error = function () {
    record('console.error', Array.prototype.join.call(arguments, ' '));
    realError.apply(console, arguments);
  };

  function later(fn) { setTimeout(fn, 10); }

  window.PigmentSDK = {
    subscribeToDataSource: function (name, opts) {
      var fx = window.FIXTURES && window.FIXTURES[name];
      later(function () {
        if (!fx) {
          record('missing fixture', name);
          if (opts && opts.onError) opts.onError(new Error('No fixture for ' + name));
          return;
        }
        if (opts && opts.onData) opts.onData({
          rows: fx.rows,
          rowOffset: 0,
          totalRowCount: fx.rows.length
        });
      });
      return {
        updateDynamicFilters: function () {},
        updateScroll: function () {},
        unsubscribe: function () {}
      };
    },
    subscribeToItems: function (alias, opts) {
      var names = (window.ITEMS && window.ITEMS[alias]) || [];
      later(function () {
        if (!window.ITEMS || !window.ITEMS[alias]) record('missing items', alias);
        if (opts && opts.onData) opts.onData({ items: names, partialResult: false });
      });
      return { unsubscribe: function () {} };
    },
    addItem: function () { return Promise.resolve(); },
    editItem: function () { return Promise.resolve(); },
    editValue: function () { return Promise.resolve(); }
  };
})();
